### ISSUE TITLE
Consider sorting the Hash if `Minitest::Test.make_my_diffs_pretty!` was used

### ISSUE THREAD

**Issue by Nakilon** [minitest/minitest#1016]
Looks like for now this setting does alias `mu_pp` directly to the `pretty_inspect` method and does not check the class.
For example, `assert_equal` diff here is wild, I can't spot the real difference:
```none
-{nil=>"ext-comp-1855-inputEl",
- "Уведомление о приёмке"=>"ext-comp-1852-inputEl",
- "Дата приемки товара"=>"ext-comp-1865-inputEl",
- "Примечания"=>"ext-comp-1869-inputEl",
- "Номер уведомления об отгрузке"=>"ext-comp-1873-inputEl",
+{"Номер уведомления об отгрузке"=>"ext-comp-1873-inputEl",
  "Дата отправки"=>"ext-comp-1877-inputEl",
  "Номер заказа"=>"ext-comp-1881-inputEl",
  "Дата заказа"=>"ext-comp-1885-inputEl",
  "Номер счет-фактуры"=>"ext-comp-1889-inputEl",
  "Дата товарной накладной"=>"ext-comp-1893-inputEl",
  "Функциональный код документа"=>"ext-comp-1861-inputEl",
- "Код документа"=>"ext-comp-1857-inputEl"}
+ "Код документа"=>"ext-comp-1857-inputEl",
+ "Уведомление о
+" + "приёмке"=>"ext-comp-1852-inputEl",
+ "Дата приемки товара"=>"ext-comp-1865-inputEl",
+ "Примечания"=>"ext-comp-1869-inputEl",
+ nil=>"ext-comp-1855-inputEl"}
```

**Comment by zenspider** [comment]
Hashes are ordered so I'm not going to add this to `mu_pp_for_diff` but you're welcome to overload it for your test or create a new assertion to sort both sides before calling `assert_equal`...

**Comment by Nakilon** [comment]
It does not matter if I sort them or not before calling `assert_equal` -- Hashes are not equal only if their data is different. In the example above one key has "\n" instead of " ". This https://github.com/minitest/minitest/blob/e4417c5b13ab917a60c218700041152136bc07c8/lib/minitest/assertions.rb#L205-L208 sounds like it makes the purpose of diff to be informative, but it isn't if we diff them unsorted.

**Comment by zenspider** [comment]
Seems to me you have 2 related but separate issues: 

1. you have 2 hashes that have different content, and you'd like to make sense of it.
2. you have 2 hashes that were assembled in different orders, making your diff unreadable.

You can:

1. ask the maintainer of the test library to sort hashes which he said he won't do because that throws away important information.
2. make the hashes have the same order, so you can easily see the differences.

which would you rather read, unsorted or sorted?:

```
  1) Failure:
TestX#test_unsorted [wtf.rb:42]:
--- expected
+++ actual
@@ -1,12 +1,13 @@
-{nil=>"ext-comp-1855-inputEl",
- "Уведомление о приёмке"=>"ext-comp-1852-inputEl",
- "Дата приемки товара"=>"ext-comp-1865-inputEl",
- "Примечания"=>"ext-comp-1869-inputEl",
- "Номер уведомления об отгрузке"=>"ext-comp-1873-inputEl",
+{"Номер уведомления об отгрузке"=>"ext-comp-1873-inputEl",
  "Дата отправки"=>"ext-comp-1877-inputEl",
  "Номер заказа"=>"ext-comp-1881-inputEl",
  "Дата заказа"=>"ext-comp-1885-inputEl",
  "Номер счет-фактуры"=>"ext-comp-1889-inputEl",
  "Дата товарной накладной"=>"ext-comp-1893-inputEl",
  "Функциональный код документа"=>"ext-comp-1861-inputEl",
- "Код документа"=>"ext-comp-1857-inputEl"}
+ "Код документа"=>"ext-comp-1857-inputEl",
+ "Уведомление о
+" + "приёмке"=>"ext-comp-1852-inputEl",
+ "Дата приемки товара"=>"ext-comp-1865-inputEl",
+ "Примечания"=>"ext-comp-1869-inputEl",
+ nil=>"ext-comp-1855-inputEl"}


  2) Failure:
TestX#test_sorted [wtf.rb:46]:
--- expected
+++ actual
@@ -8,5 +8,6 @@
  "Номер счет-фактуры"=>"ext-comp-1889-inputEl",
  "Номер уведомления об отгрузке"=>"ext-comp-1873-inputEl",
  "Примечания"=>"ext-comp-1869-inputEl",
- "Уведомление о приёмке"=>"ext-comp-1852-inputEl",
+ "Уведомление о
+" + "приёмке"=>"ext-comp-1852-inputEl",
  "Функциональный код документа"=>"ext-comp-1861-inputEl"}
```
via something like:
```ruby
  def assert_equal_hash exp, act
    maybe_nil = ->((k,v)) { [k||"", v] } # jump through hoops if key is nil
    assert_equal exp.sort_by(&maybe_nil).to_h, act.sort_by(&maybe_nil).to_h
  end
```

**Comment by zenspider** [comment]
Please close this if you think it has been resolved.

**Comment by Nakilon** [comment]
You propose me to make own assertion method that wraps the `assert_equal` with some sorting block if it's a Hash (also maybe sort values recursively if they are Hashes too). I think it would be a useful built-in feature for those who wants to use `make_my_diffs_pretty!`. Though I agree, it's complicated due to incomparable classes so you had to make that conditional in the example solution but maybe it's possible to come up with some universal reliable approach, idk.
Personally I'm not the one running the tests or reviewing the regression reports -- I'm the one who for now makes the framework and has other things in the backlog so I can just decide to not give a shit and when after some weeks someone would ask "wtf" I'd say "/shrug" and link this GitHub issue. But maybe within a month or so someone else will stumble upon this issue and say "me too". I would like to know if there are other people who would like this feature. But I know that you like the Issues here to be closed and then frozen, so you decide. Feel free to close if you are sure minitest should not have this implemented or discussed.

**Comment by havenwood** [comment]
@Nakilon reordering a Hash is sus since they're ordered. Since Ruby 1.9, order matters apart from equality and shuffling them can be incredibly confusing since it's not allowed by the Ruby spec. They're ordered and need to stay in their order.

Your example seems like it would be better as a Struct or Data, which get their order up front when members are defined rather than on key insertion. Both Struct and Data would diff nicely, whichever order you insert members.

**Comment by havenwood** [comment]
I agree there's some awkwardness around Hash equality and order that's probably a remnant of attempts at backwards compatibility with Ruby 1.8 when Hashes became ordered in 1.9.

That said, there haven't been a ton of issues complaining about it over the years. There was one request for an OrderedHash alias that was rejected, since Hashes are documented as ordered now. This bug tracker issue is for sure related, but I don't think anyone followed up on requesting a separate equality-with-order method: https://bugs.ruby-lang.org/issues/11508

I don't think changing the default to sort Hashes at the library level is viable for the sake of a prettier diff, unfortunately. It might be worth considering raising an upstream issue with the Ruby bug tracker if you have the repeated need and a proposal. I'd personally lean towards using a different data structure for this particular use case.

**Comment by zenspider** [comment]
Been a month. Literally nobody is clamoring for this. Closing.

**Comment by Nakilon** [comment]
> @Nakilon reordering a Hash is sus since they're ordered. Since Ruby 1.9, order matters apart from equality and shuffling them can be incredibly confusing since it's not allowed by the Ruby spec. They're ordered and need to stay in their order.
> 
> Your example seems like it would be better as a Struct or Data, which get their order up front when members are defined rather than on key insertion. Both Struct and Data would diff nicely, whichever order you insert members.

Yeah, but rspec proved comparing order-agnostically is needed and made `match_array`.
