### ISSUE TITLE
Can you support equivalent of rspec before(:all)

### ISSUE THREAD

**Issue by gtd** [minitest/minitest#61]
That is a setup that runs once per TestCase.  I've done some crazy things to work around this in test/unit over the years, and it's hard to believe that I've never seen it anywhere but rspec.  If I have some time I might work on a patch, but I'm buried at the moment.  Thoughts?

**Comment by timruffles** [comment]
@bbozo's use case is why I'm here.

If you're not keen to add it, would you accept a documentation PR to describe how to work around it? For transactional fixtures this is my current workaround:

```ruby
def setup
  before_all
end

@@before_all_run = false

def before_all
  return if @@before_all_run
  @@before_all_run = true
  
  # do whatever creates the records - e.g making HTTP requests

  # cache records here to avoid the DB rollbacks in the assertions below
  @@some_record = SomeRecord.find(some_id)
end

def test_something_about_record
    # one assertion
end

 def test_something_else_about_record
    # one assertion
end

# more tests

```

**Comment by science** [comment]
Per @timruffles and @bbozo comments, I'm a little confused what the dispute is about.

I have an time consuming set of database loads to run. They are the same for every test case in a given suite. I use DatabaseCleaner to rollback changes between each test case. I would like to load that data before the entire suite runs, and then truncate all the data after the entire suite finishes. This will shave quite a bit of time off my full test package.

The reason I want something in the framework is that I use a set of my own classes that my tests suites inherit from depending on what services they need. I have a "DBTest" and and "WebAppTest" which descends from DBTest.

I can engineer this myself, as others have discussed, but having a hook in the test harness would make it simple super simple for me:
```ruby 
class DBTest < MiniTest::Test
  def before_suite 
    super
    Utils.seed_all
  end
  def after_suite
    super
    Utils.truncate_all
  end
end
# then my test suites can just descend from DBTest and get that capability if they want it. 
```
If I had a choice, I'd greatly prefer the above method hooks to class method calls (`before_suite { code }`) because it makes it easier to move these things into mix-ins, prevent them from being run in conditional circumstances etc.

After reading through this thread, I'm still not at all clear why this is a bad idea or why Minitest shouldn't support this capability. Obviously it's six feet of rope for people to create heinous test dependencies if they go that route, but there are already lots of others ways to hang your test suite, I think.
