### ISSUE TITLE
Duplicate class names cause issues

### ISSUE THREAD

**Issue by danman01** [minitest/minitest#925]
I propose multiple classes with the same name results in a warning when Minitest encounters the duplicate class, or when starting up. I don't think this is a bug by any means, but more of an enhancement / way to idiot-proof the library.

We have a large project with nested classes, and when someone attempted to write a test with a class that had already been used (by omitting the namespace...tsk tsk), there were Strange Things that started happening. I determined with a lot of breakpoints and trial and error that the setup block wouldn't run for the duplicated class name, but the teardown block would...Anyways, I propose a WARNING: Duplicate Class Names detected! when minitest spins up and hits one of these duplicated classes. If this is something other people may find helpful, it would be a nice opportunity for me to dig into the code and try a contribution...what does the community think?

**Comment by zenspider** [comment]
If you're talking about `class TestBlah < Minitest::Test`, then I don't think there's anything I can really do about that... Reopening a class and extending it is a superpower of ruby, but also comes with some serious need for responsible use. This is a good case of it. 

If you ran your tests with `-w` on (which many rails apps don't because they're ... well, rails apps... .but also because several popular libraries aren't `-w` clean) then you would probably see that `setup` was being re-defined... I assume only one side of this reopened class had a `teardown` and that's why it was more consistent.

BUT... if you're talking about `describe Blah` .... well... I dunno. It is MEANT to be able to be used with forms like:

```ruby
describe Blah, :normal { ... }
describe Blah, :edgecase { ... }
# ... etc
```

What's your actual scenario (not enough info above) and what are you suggesting changes?

**Comment by blowmage** [comment]
@danman01 ping

**Comment by zenspider** [comment]
No response... Closing.
