### ISSUE TITLE
Feature request for Mock#verify to accept a custom message arg

### ISSUE THREAD

**Issue by Nakilon** [minitest/minitest#971]
BTW, maybe also add them to assertions count in the end report because it has surprised me few minutes ago that my test suite has more tests than assertions.

**Comment by zenspider** [comment]
See `assert_mock`... but it doesn't take a custom message ATM. I can add that.

**Comment by Nakilon** [comment]
BTW didn't know `#verify` returns anything. But how can it return not `true`? I see only raising.

**Comment by Nakilon** [comment]
Oh, you mean `assert_mock` would just increment the counter?

**Comment by zenspider** [comment]
Hrm... Now I'm less sure this is an OK change:

```diff
--- old/lib/minitest/mock.rb
+++ new/lib/minitest/mock.rb
@@ -245,8 +245,11 @@
   ##
   # Assert that the mock verifies correctly.
 
-  def assert_mock mock
+  def assert_mock mock, msg = nil
     assert mock.verify
+  rescue MockExpectationError => e
+    msg = message(msg) { "Expected mock to verify, got: #{e.message}" }
+    flunk msg
   end
 end
```

All mock mismatches before raised an error, this will convert them to failing (F instead of E). Does it matter? I don't know. I think when you're using `assert_X` you expect it not to error so I could reason this as a bug in `assert_mock`.

**Comment by armellarcier** [comment]
> All mock mismatches before raised an error, this will convert them to failing (F instead of E). Does it matter? I don't know. I think when you're using `assert_X` you expect it not to error so I could reason this as a bug in `assert_mock`.

I was just looking for info as to why assert_mock was raising an error instead of failing the test.

Also, it does not increment the assertions count.

I was also wondering wether there is a way to write asser_mock with the expect keyword, or the `_` alias.

A member of my team suggested something like `_(mock.verify).wont_raise` or `_(mock.verify).must_equal true`

We settled on keeping `assert_mock mock` even though it goes to errors instead of failures.

**Comment by maxim** [comment]
To me it makes sense for `mock.verify` to raise (E) since it's not an assertion, and for `assert_mock` to fail (F) since it is. The current `assert_mock` implementation has gotta be a bug, since having `assert` there does nothing.

Generally, I'm not sure why we have 2 ways to flunk a mock, but it doesn't bother me. I'm +1 on the above [diff](https://github.com/minitest/minitest/issues/971#issuecomment-1781741980).

**Comment by zenspider** [comment]
I've fixed `assert_mock` as well as adding a `verify_mock` expectation.
